FROM python:3.8-slim

WORKDIR /app

COPY requirements-estimator.txt requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends libgomp1 && \
    rm -rf /var/lib/apt/lists/* /tmp/* && \
    pip install --no-cache-dir -qq -r requirements.txt

COPY docker-entrypoint.sh docker-entrypoint.sh
COPY ./app/estimator /app

ENTRYPOINT [ "/app/docker-entrypoint.sh" ]
