FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim

COPY requirements-serve.txt /app/requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends libgomp1 && \
    rm -rf /var/lib/apt/lists/* /tmp/* && \
    pip install --no-cache-dir -qq -r /app/requirements.txt

COPY ./app/main.py,./app/preprocess.py /app/
